services:

  db:
    image: postgres
    restart: always
    env_file: ".env"
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
