import type { Prisma } from "@prisma/client";
import type { NTTKey } from "./entities-type";

export interface DeleteManyArgs {
    User: Prisma.UserDeleteManyArgs;
    Account: Prisma.AccountDeleteManyArgs;
    Session: Prisma.SessionDeleteManyArgs;
    VerificationToken: Prisma.VerificationTokenDeleteManyArgs;
    Authenticator: Prisma.AuthenticatorDeleteManyArgs;
    Payment: Prisma.PaymentDeleteManyArgs;
    Appointment: Prisma.AppointmentDeleteManyArgs;
    AppointmentType: Prisma.AppointmentTypeDeleteManyArgs;
    Location: Prisma.LocationDeleteManyArgs;
    Patient: Prisma.PatientDeleteManyArgs;
    Provider: Prisma.ProviderDeleteManyArgs;
    Form: Prisma.FormDeleteManyArgs;
    FormEncounter: Prisma.FormEncounterDeleteManyArgs;
    FormResource: Prisma.FormResourceDeleteManyArgs;
    FormSubmission: Prisma.FormSubmissionDeleteManyArgs;
    Field: Prisma.FieldDeleteManyArgs;
    FieldAnswer: Prisma.FieldAnswerDeleteManyArgs;
    FieldOption: Prisma.FieldOptionDeleteManyArgs;
    Encounter: Prisma.EncounterDeleteManyArgs;
    EncounterType: Prisma.EncounterTypeDeleteManyArgs;
    Obs: Prisma.ObsDeleteManyArgs;
    Order: Prisma.OrderDeleteManyArgs;
    OrderFrequency: Prisma.OrderFrequencyDeleteManyArgs;
    OrderRoute: Prisma.OrderRouteDeleteManyArgs;
    OrderType: Prisma.OrderTypeDeleteManyArgs;
    OrderUnit: Prisma.OrderUnitDeleteManyArgs;
    Concept: Prisma.ConceptDeleteManyArgs;
    ConceptAnswer: Prisma.ConceptAnswerDeleteManyArgs;
    ConceptClass: Prisma.ConceptClassDeleteManyArgs;
    ConceptDatatype: Prisma.ConceptDatatypeDeleteManyArgs;
    ConceptMap: Prisma.ConceptMapDeleteManyArgs;
    ConceptName: Prisma.ConceptNameDeleteManyArgs;
    ConceptNumeric: Prisma.ConceptNumericDeleteManyArgs;
    ConceptProposal: Prisma.ConceptProposalDeleteManyArgs;
    ConceptSet: Prisma.ConceptSetDeleteManyArgs;
    ConceptSource: Prisma.ConceptSourceDeleteManyArgs;
    ConceptWord: Prisma.ConceptWordDeleteManyArgs;
    Resource: Prisma.ResourceDeleteManyArgs;
    BlogPost: Prisma.BlogPostDeleteManyArgs;
    BlogPostTag: Prisma.BlogPostTagDeleteManyArgs;
    BlogPostTagArrow: Prisma.BlogPostTagArrowDeleteManyArgs;
    BlogPostAuthor: Prisma.BlogPostAuthorDeleteManyArgs;
    SpaceTimeCoordinates: Prisma.SpaceTimeCoordinatesDeleteManyArgs;
    BudgetEntry: Prisma.BudgetEntryDeleteManyArgs;
    Service: Prisma.ServiceDeleteManyArgs;
    Budget: Prisma.BudgetDeleteManyArgs;
    Report: Prisma.ReportDeleteManyArgs;
    BudUser: Prisma.BudUserDeleteManyArgs;
    BudgetBudUser: Prisma.BudgetBudUserDeleteManyArgs;
    BudEvent: Prisma.BudEventDeleteManyArgs;
}

export type DeleteManyArgType<T extends NTTKey> = DeleteManyArgs[T];
