import type { Prisma } from "@prisma/client";
import type { NTTKey } from "./entities-type";

export interface DeleteArgs {
    Principal: Prisma.PrincipalDeleteArgs;
    Account: Prisma.AccountDeleteArgs;
    Session: Prisma.SessionDeleteArgs;
    VerificationToken: Prisma.VerificationTokenDeleteArgs;
    Authenticator: Prisma.AuthenticatorDeleteArgs;
    Payment: Prisma.PaymentDeleteArgs;
    Appointment: Prisma.AppointmentDeleteArgs;
    AppointmentType: Prisma.AppointmentTypeDeleteArgs;
    Location: Prisma.LocationDeleteArgs;
    Patient: Prisma.PatientDeleteArgs;
    Equipment: Prisma.EquipmentDeleteArgs;
    Service: Prisma.ServiceDeleteArgs;
    Provider: Prisma.ProviderDeleteArgs;
    Form: Prisma.FormDeleteArgs;
    FormEncounter: Prisma.FormEncounterDeleteArgs;
    FormResource: Prisma.FormResourceDeleteArgs;
    FormSubmission: Prisma.FormSubmissionDeleteArgs;
    Field: Prisma.FieldDeleteArgs;
    FieldAnswer: Prisma.FieldAnswerDeleteArgs;
    FieldOption: Prisma.FieldOptionDeleteArgs;
    Encounter: Prisma.EncounterDeleteArgs;
    EncounterType: Prisma.EncounterTypeDeleteArgs;
    Obs: Prisma.ObsDeleteArgs;
    Order: Prisma.OrderDeleteArgs;
    OrderFrequency: Prisma.OrderFrequencyDeleteArgs;
    OrderRoute: Prisma.OrderRouteDeleteArgs;
    OrderType: Prisma.OrderTypeDeleteArgs;
    OrderUnit: Prisma.OrderUnitDeleteArgs;
    Concept: Prisma.ConceptDeleteArgs;
    ConceptAnswer: Prisma.ConceptAnswerDeleteArgs;
    ConceptClass: Prisma.ConceptClassDeleteArgs;
    ConceptDatatype: Prisma.ConceptDatatypeDeleteArgs;
    ConceptMap: Prisma.ConceptMapDeleteArgs;
    ConceptName: Prisma.ConceptNameDeleteArgs;
    ConceptNumeric: Prisma.ConceptNumericDeleteArgs;
    ConceptProposal: Prisma.ConceptProposalDeleteArgs;
    ConceptSet: Prisma.ConceptSetDeleteArgs;
    ConceptSource: Prisma.ConceptSourceDeleteArgs;
    ConceptWord: Prisma.ConceptWordDeleteArgs;
    Resource: Prisma.ResourceDeleteArgs;
    BlogPost: Prisma.BlogPostDeleteArgs;
    BlogPostTag: Prisma.BlogPostTagDeleteArgs;
    BlogPostTagArrow: Prisma.BlogPostTagArrowDeleteArgs;
    BlogPostAuthor: Prisma.BlogPostAuthorDeleteArgs;
    SpaceTimeCoordinates: Prisma.SpaceTimeCoordinatesDeleteArgs;
    BudgetEntry: Prisma.BudgetEntryDeleteArgs;
    BudgetService: Prisma.BudgetServiceDeleteArgs;
    Budget: Prisma.BudgetDeleteArgs;
    Report: Prisma.ReportDeleteArgs;
    BudUser: Prisma.BudUserDeleteArgs;
    BudgetBudUser: Prisma.BudgetBudUserDeleteArgs;
    BudEvent: Prisma.BudEventDeleteArgs;
}

export type DeleteArgType<T extends NTTKey> = DeleteArgs[T];
