import type { Prisma } from "@prisma/client";
import type { NTTKey } from "./entities-type";

export interface FieldRefs {
    Principal: Prisma.PrincipalFieldRefs;
    Account: Prisma.AccountFieldRefs;
    Session: Prisma.SessionFieldRefs;
    VerificationToken: Prisma.VerificationTokenFieldRefs;
    Authenticator: Prisma.AuthenticatorFieldRefs;
    Payment: Prisma.PaymentFieldRefs;
    Appointment: Prisma.AppointmentFieldRefs;
    AppointmentType: Prisma.AppointmentTypeFieldRefs;
    Location: Prisma.LocationFieldRefs;
    Patient: Prisma.PatientFieldRefs;
    Equipment: Prisma.EquipmentFieldRefs;
    Service: Prisma.ServiceFieldRefs;
    Provider: Prisma.ProviderFieldRefs;
    Form: Prisma.FormFieldRefs;
    FormEncounter: Prisma.FormEncounterFieldRefs;
    FormResource: Prisma.FormResourceFieldRefs;
    FormSubmission: Prisma.FormSubmissionFieldRefs;
    Field: Prisma.FieldFieldRefs;
    FieldAnswer: Prisma.FieldAnswerFieldRefs;
    FieldOption: Prisma.FieldOptionFieldRefs;
    Encounter: Prisma.EncounterFieldRefs;
    EncounterType: Prisma.EncounterTypeFieldRefs;
    Obs: Prisma.ObsFieldRefs;
    Order: Prisma.OrderFieldRefs;
    OrderFrequency: Prisma.OrderFrequencyFieldRefs;
    OrderRoute: Prisma.OrderRouteFieldRefs;
    OrderType: Prisma.OrderTypeFieldRefs;
    OrderUnit: Prisma.OrderUnitFieldRefs;
    Concept: Prisma.ConceptFieldRefs;
    ConceptAnswer: Prisma.ConceptAnswerFieldRefs;
    ConceptClass: Prisma.ConceptClassFieldRefs;
    ConceptDatatype: Prisma.ConceptDatatypeFieldRefs;
    ConceptMap: Prisma.ConceptMapFieldRefs;
    ConceptName: Prisma.ConceptNameFieldRefs;
    ConceptNumeric: Prisma.ConceptNumericFieldRefs;
    ConceptProposal: Prisma.ConceptProposalFieldRefs;
    ConceptSet: Prisma.ConceptSetFieldRefs;
    ConceptSource: Prisma.ConceptSourceFieldRefs;
    ConceptWord: Prisma.ConceptWordFieldRefs;
    Resource: Prisma.ResourceFieldRefs;
    BlogPost: Prisma.BlogPostFieldRefs;
    BlogPostTag: Prisma.BlogPostTagFieldRefs;
    BlogPostTagArrow: Prisma.BlogPostTagArrowFieldRefs;
    BlogPostAuthor: Prisma.BlogPostAuthorFieldRefs;
    SpaceTimeCoordinates: Prisma.SpaceTimeCoordinatesFieldRefs;
    BudgetEntry: Prisma.BudgetEntryFieldRefs;
    BudgetService: Prisma.BudgetServiceFieldRefs;
    Budget: Prisma.BudgetFieldRefs;
    Report: Prisma.ReportFieldRefs;
    BudUser: Prisma.BudUserFieldRefs;
    BudgetBudUser: Prisma.BudgetBudUserFieldRefs;
    BudEvent: Prisma.BudEventFieldRefs;
}

export type FieldRefType<T extends NTTKey> = FieldRefs[T];
