import type { Prisma } from "@prisma/client";
import type { NTTKey } from "./entities-type";

export interface GroupByArgs {
    User: Prisma.UserGroupByArgs;
    Account: Prisma.AccountGroupByArgs;
    Session: Prisma.SessionGroupByArgs;
    VerificationToken: Prisma.VerificationTokenGroupByArgs;
    Authenticator: Prisma.AuthenticatorGroupByArgs;
    Payment: Prisma.PaymentGroupByArgs;
    Appointment: Prisma.AppointmentGroupByArgs;
    AppointmentType: Prisma.AppointmentTypeGroupByArgs;
    Location: Prisma.LocationGroupByArgs;
    Patient: Prisma.PatientGroupByArgs;
    Provider: Prisma.ProviderGroupByArgs;
    Form: Prisma.FormGroupByArgs;
    FormEncounter: Prisma.FormEncounterGroupByArgs;
    FormResource: Prisma.FormResourceGroupByArgs;
    FormSubmission: Prisma.FormSubmissionGroupByArgs;
    Field: Prisma.FieldGroupByArgs;
    FieldAnswer: Prisma.FieldAnswerGroupByArgs;
    FieldOption: Prisma.FieldOptionGroupByArgs;
    Encounter: Prisma.EncounterGroupByArgs;
    EncounterType: Prisma.EncounterTypeGroupByArgs;
    Obs: Prisma.ObsGroupByArgs;
    Order: Prisma.OrderGroupByArgs;
    OrderFrequency: Prisma.OrderFrequencyGroupByArgs;
    OrderRoute: Prisma.OrderRouteGroupByArgs;
    OrderType: Prisma.OrderTypeGroupByArgs;
    OrderUnit: Prisma.OrderUnitGroupByArgs;
    Concept: Prisma.ConceptGroupByArgs;
    ConceptAnswer: Prisma.ConceptAnswerGroupByArgs;
    ConceptClass: Prisma.ConceptClassGroupByArgs;
    ConceptDatatype: Prisma.ConceptDatatypeGroupByArgs;
    ConceptMap: Prisma.ConceptMapGroupByArgs;
    ConceptName: Prisma.ConceptNameGroupByArgs;
    ConceptNumeric: Prisma.ConceptNumericGroupByArgs;
    ConceptProposal: Prisma.ConceptProposalGroupByArgs;
    ConceptSet: Prisma.ConceptSetGroupByArgs;
    ConceptSource: Prisma.ConceptSourceGroupByArgs;
    ConceptWord: Prisma.ConceptWordGroupByArgs;
    Resource: Prisma.ResourceGroupByArgs;
    BlogPost: Prisma.BlogPostGroupByArgs;
    BlogPostTag: Prisma.BlogPostTagGroupByArgs;
    BlogPostTagArrow: Prisma.BlogPostTagArrowGroupByArgs;
    BlogPostAuthor: Prisma.BlogPostAuthorGroupByArgs;
    SpaceTimeCoordinates: Prisma.SpaceTimeCoordinatesGroupByArgs;
    BudgetEntry: Prisma.BudgetEntryGroupByArgs;
    Service: Prisma.ServiceGroupByArgs;
    Budget: Prisma.BudgetGroupByArgs;
    Report: Prisma.ReportGroupByArgs;
    BudUser: Prisma.BudUserGroupByArgs;
    BudgetBudUser: Prisma.BudgetBudUserGroupByArgs;
    BudEvent: Prisma.BudEventGroupByArgs;
}

export type GroupByArgType<T extends NTTKey> = GroupByArgs[T];
