import type { Prisma } from "@prisma/client";
import type { NTTKey } from "./entities-type";

export interface Inclusions {
    Principal: Prisma.PrincipalInclude;
    Account: Prisma.AccountInclude;
    Session: Prisma.SessionInclude;
    VerificationToken: Prisma.VerificationTokenInclude;
    Authenticator: Prisma.AuthenticatorInclude;
    Payment: Prisma.PaymentInclude;
    Appointment: Prisma.AppointmentInclude;
    AppointmentType: Prisma.AppointmentTypeInclude;
    Location: Prisma.LocationInclude;
    Patient: Prisma.PatientInclude;
    Equipment: Prisma.EquipmentInclude;
    Service: Prisma.ServiceInclude;
    Provider: Prisma.ProviderInclude;
    Form: Prisma.FormInclude;
    FormEncounter: Prisma.FormEncounterInclude;
    FormResource: Prisma.FormResourceInclude;
    FormSubmission: Prisma.FormSubmissionInclude;
    Field: Prisma.FieldInclude;
    FieldAnswer: Prisma.FieldAnswerInclude;
    FieldOption: Prisma.FieldOptionInclude;
    Encounter: Prisma.EncounterInclude;
    EncounterType: Prisma.EncounterTypeInclude;
    Obs: Prisma.ObsInclude;
    Order: Prisma.OrderInclude;
    OrderFrequency: Prisma.OrderFrequencyInclude;
    OrderRoute: Prisma.OrderRouteInclude;
    OrderType: Prisma.OrderTypeInclude;
    OrderUnit: Prisma.OrderUnitInclude;
    Concept: Prisma.ConceptInclude;
    ConceptAnswer: Prisma.ConceptAnswerInclude;
    ConceptClass: Prisma.ConceptClassInclude;
    ConceptDatatype: Prisma.ConceptDatatypeInclude;
    ConceptMap: Prisma.ConceptMapInclude;
    ConceptName: Prisma.ConceptNameInclude;
    ConceptNumeric: Prisma.ConceptNumericInclude;
    ConceptProposal: Prisma.ConceptProposalInclude;
    ConceptSet: Prisma.ConceptSetInclude;
    ConceptSource: Prisma.ConceptSourceInclude;
    ConceptWord: Prisma.ConceptWordInclude;
    Resource: Prisma.ResourceInclude;
    BlogPost: Prisma.BlogPostInclude;
    BlogPostTag: Prisma.BlogPostTagInclude;
    BlogPostTagArrow: Prisma.BlogPostTagArrowInclude;
    BlogPostAuthor: Prisma.BlogPostAuthorInclude;
    SpaceTimeCoordinates: Prisma.SpaceTimeCoordinatesInclude;
    BudgetEntry: Prisma.BudgetEntryInclude;
    BudgetService: Prisma.BudgetServiceInclude;
    Budget: Prisma.BudgetInclude;
    Report: Prisma.ReportInclude;
    BudUser: Prisma.BudUserInclude;
    BudgetBudUser: Prisma.BudgetBudUserInclude;
    BudEvent: Prisma.BudEventInclude;
}

export type InclusionType<T extends NTTKey> = Inclusions[T];
